FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
MAINTAINER Matt ter Steege <matttersteege@gmail.com>
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["ChemCourses/ChemCourses.csproj", "ChemCourses/"]
COPY ["BetterPages/BetterPages.csproj", "BetterPages/"]
RUN dotnet restore "ChemCourses/ChemCourses.csproj"
COPY . .
WORKDIR "/src/ChemCourses"
RUN dotnet build "ChemCourses.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ChemCourses.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app

# Copy the video files into the container
COPY ChemCourses/wwwroot/videos /app/videos
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ChemCourses.dll"]

#hit the [ChemCourses/Dockerfile - orange pi] run button and all will be handled automatically